apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-service.fullname" . }}-config
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
data:
  database.host: {{ .Values.config.database.host | quote }}
  database.port: {{ .Values.config.database.port | quote }}
  database.name: {{ .Values.config.database.name | quote }}
  database.sslmode: {{ .Values.config.database.sslmode | quote }}
  redis.host: {{ .Values.config.redis.host | quote }}
  redis.port: {{ .Values.config.redis.port | quote }}
  ml-service.url: {{ .Values.config.mlService.url | quote }}
